In [ ]:
import torch
# imports pytorch

In [ ]:
import numpy as np
# imports numpy

**Simple Tensor Operations**

In [ ]:
a = torch.empty(3,4)
a.size()
a
# creates an empty tensor of shape (3,4)

tensor([[2.3822e-44, 4.4182e-41, 0.0000e+00, 0.0000e+00],
        [3.3631e-44, 4.4182e-41, 1.3739e-38, 0.0000e+00],
        [1.4013e-45, 4.4182e-41, 5.1749e-33, 4.4182e-41]])

In [ ]:
a.fill_(3.14)
# inplace operations are suffixed with an underscore
# fills all the elements of tensor a with 3.14

tensor([[3.1400, 3.1400, 3.1400, 3.1400],
        [3.1400, 3.1400, 3.1400, 3.1400],
        [3.1400, 3.1400, 3.1400, 3.1400]])

In [ ]:
a.mean()
# computes the average of the tensor a
# even a single element of a tensor is a tensor (0D)

tensor(3.1400)

In [ ]:
a[1,2]
# even a single element of a tensor is a tensor (0D)

tensor(3.1400)

In [ ]:
a.std()
# returns the standard deviation of elements in tensor a

tensor(4.9804e-07)

In [ ]:
a.sum()
# returns the sum of elements in tensor a

tensor(37.6800)

In [ ]:
a.sum().item()
# to convert a 0D tensor into a Python scalar, item() is used

37.679996490478516

In [ ]:
b = torch.randint(0, 10, (3, 3))
b
# Random integers between 0 and 9

tensor([[1, 1, 7],
        [5, 3, 6],
        [0, 0, 6]])

In [ ]:
b = torch.randn(5, 10)
b
# Random values from a normal distribution (mean=0, std=1)

tensor([[ 1.1528,  0.3063,  0.1983,  0.5385,  0.6547, -1.1175,  0.7949,  1.2248,
          0.4897, -0.3720],
        [ 0.8460, -0.8868,  1.5620,  2.8107, -0.2721,  1.7704,  1.1516,  0.6803,
         -0.0589, -0.9159],
        [-1.0242, -1.6443,  0.2699,  0.4544,  0.2495, -0.1583,  1.8618, -1.4824,
         -0.8515,  1.5297],
        [ 1.5095, -0.1405,  1.8925, -0.7567, -0.0495,  0.5960, -0.6705, -0.7421,
          1.8881, -1.0480],
        [-0.0196,  0.7002, -0.9930, -0.6535, -0.2605, -0.7249,  0.7740,  1.1029,
         -0.8934, -1.3175]])

In [ ]:
print(b.mean().item(), b.std().item())

0.19911064207553864 1.0479155778884888


**Vector/matrix Operations**

In [ ]:
x = torch.tensor([1.0, 3.0, 5.0])
y = torch.tensor([2.0, 4.0, 6.0])
x+y

tensor([ 3.,  7., 11.])

In [ ]:
x*y
# hadamard product

tensor([ 2., 12., 30.])

In [ ]:
x**2
# exponentiation

tensor([ 1.,  9., 25.])

In [ ]:
x**y
# element-wise exponentiation

tensor([1.0000e+00, 8.1000e+01, 1.5625e+04])

In [ ]:
m=torch.tensor([[1.0, 0.0, 0.0],[0.0, 2.0, 0.0],[0.0, 0.0, 3.0]])
# matrix (2D tensor) intialization

In [ ]:
m.mv(x)
# matrix-vector product

tensor([ 1.,  6., 15.])

In [ ]:
m@x
# another form for the matrix-vector product

tensor([ 1.,  6., 15.])

**Slicing is similar to Numpy**

In [ ]:
a=torch.empty(2,5).random_(10)
a
# initialize the tensor with random integers below 10

tensor([[0., 8., 0., 1., 4.],
        [5., 4., 3., 5., 4.]])

In [ ]:
a[0]

tensor([0., 8., 0., 1., 4.])

In [ ]:
a[1]

tensor([5., 4., 3., 5., 4.])

In [ ]:
a[:,3:]
# slicing the tensor with a range

tensor([[1., 4.],
        [5., 4.]])

In [ ]:
a[:,1:3:2] = -1.0
a

tensor([[ 0., -1.,  0.,  1.,  4.],
        [ 5., -1.,  3.,  5.,  4.]])

In [ ]:
# Original tensor `a`
print("Tensor `a`:")
print(a)

# Cloning `a` into `b`
b = a.clone()
print("\nCloned Tensor `b` (before modification):")
print(b)

# Modifying `b` with Boolean indexing
b[b < 3] = -1
print("\nModified Tensor `b` (values < 3 replaced with -1):")
print(b)

# Checking if `a` remains unchanged
print("\nTensor `a` after modifying `b` (unchanged):")
print(a)

Tensor `a`:
tensor([[ 0., -1.,  0.,  1.,  4.],
        [ 5., -1.,  3.,  5.,  4.]])

Cloned Tensor `b` (before modification):
tensor([[ 0., -1.,  0.,  1.,  4.],
        [ 5., -1.,  3.,  5.,  4.]])

Modified Tensor `b` (values < 3 replaced with -1):
tensor([[-1., -1., -1., -1.,  4.],
        [ 5., -1.,  3.,  5.,  4.]])

Tensor `a` after modifying `b` (unchanged):
tensor([[ 0., -1.,  0.,  1.,  4.],
        [ 5., -1.,  3.,  5.,  4.]])


In [ ]:
# Demonstrating assignment (reference) for comparison
c = a
c[c > 2] = 10
print("\nAssigned Tensor `c` (values > 2 replaced with 10):")
print(c)

# Checking if `a` changes with `c`
print("\nTensor `a` after modifying `c` (changed due to reference):")
print(a)



Assigned Tensor `c` (values > 2 replaced with 10):
tensor([[ 0., -1.,  0.,  1., 10.],
        [10., -1., 10., 10., 10.]])

Tensor `a` after modifying `c` (changed due to reference):
tensor([[ 0., -1.,  0.,  1., 10.],
        [10., -1., 10., 10., 10.]])


**High demnsional tensors**

In [ ]:
za = torch.zeros(1,3)
za.dtype, za.device
# default tensor is float32 type stored in CPU memory

(torch.float32, device(type='cpu'))

In [ ]:
za

tensor([[0., 0., 0.]])

In [ ]:
# za=za.to(torch.float64)
za=za.long()
za.dtype, za.device

(torch.int64, device(type='cpu'))

In [ ]:
if torch.cuda.is_available():
  device = torch.device("cuda")

  za = za.to(device)
za.dtype, za.device

(torch.int64, device(type='cuda', index=0))

In [ ]:
x=torch.tensor([[1, 2., 3],
                [4, 5, 6]])
x

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [ ]:
x.t()
# x.T
# transposing a tensor

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])

In [ ]:
x.view(-1)
# reduce/reshape the tensor into a single dimensional (1D) tensor
# in the raster-scan order (rows first then columns)

tensor([1., 2., 3., 4., 5., 6.])

In [ ]:
x=torch.tensor([[1, 2., 3],
                [4, 5, 6],
                [7, 8., 9],
                [10, 11, 12]])
x

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])

In [ ]:
x.view(3,-1)
# reshape into a tensor with 3 rows and whatever is the resulting columns
# in the raster-scan order

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])

**Pytorch is an immense library of tensor operations. Visit documentation for a better idea and practice more to familiarize the important operations.**


**For efficiency reasons, different tensors share the same data, therefore need to be careful when modifying. By default, do not assume that two tensors refer to different data in memory**

In [ ]:
a = torch.full((2,5),2)
a

tensor([[2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2]])

In [ ]:
b=a.view(-1)
b

tensor([2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [ ]:
a[1,4]=10
a

tensor([[ 2,  2,  2,  2,  2],
        [ 2,  2,  2,  2, 10]])

In [ ]:
print(b)
b[1] = 9
print(b)

tensor([ 2,  2,  2,  2,  2,  2,  2,  2,  2, 10])
tensor([ 2,  9,  2,  2,  2,  2,  2,  2,  2, 10])


In [ ]:
a
# b shares the same memory as a, meaning changes to one will reflect in the other

tensor([[ 2,  9,  2,  2,  2],
        [ 2,  2,  2,  2, 10]])

**Broadcasting and Einstein Summations**

In [ ]:
# Broadcasting automatically expands the dimensions by replicating coefficients (when required)
x = torch.empty(100,3).normal_(3)
x.mean(0)

tensor([3.0955, 3.0641, 2.8406])

In [ ]:
x -= x.mean(0)
# we subtract 1 X 3 tensor from 100 X 3 tensor; it should result in an error, but it works!

x.mean(0)

tensor([-1.0014e-07, -3.3379e-08,  2.3365e-07])

In [ ]:
A = torch.tensor([[1.],[2.],[3.],[4.],[5.]])
B = torch.tensor([[5., -5., 5., -5., 5.]])
print(A.shape,B.shape)
A+B

torch.Size([5, 1]) torch.Size([1, 5])


tensor([[ 6., -4.,  6., -4.,  6.],
        [ 7., -3.,  7., -3.,  7.],
        [ 8., -2.,  8., -2.,  8.],
        [ 9., -1.,  9., -1.,  9.],
        [10.,  0., 10.,  0., 10.]])

**Einsten Summation Convention**

Provides a concise way of describing dimension re-ordering, summing component wise products along some of them.

we can use for matrix multiplication, matrix-vector product, diagonal extraction, Hadamard product, batch matrix product, etc.

In [ ]:
A = torch.rand(2,5)
B = torch.rand(5,4)
torch.einsum('ij,jk->ik',A,B)

tensor([[1.8589, 1.6150, 1.0845, 1.9010],
        [1.7351, 1.6737, 1.2860, 2.0597]])

In [ ]:
A@B

tensor([[1.8589, 1.6150, 1.0845, 1.9010],
        [1.7351, 1.6737, 1.2860, 2.0597]])